language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - "git submodule update --init --recursive"

before_script:
  - "composer install --prefer-dist"

script:
  # Standard build script
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]] ; then vendor/bin/phing test; fi
  # HHVM script (phing not currently supported on hhvm pending http://www.phing.info/trac/ticket/1086)
  - if [[ $TRAVIS_PHP_VERSION == "hhvm" ]] ; then ./vendor/bin/phpunit --bootstrap=modules/unittest/bootstrap_all_modules.php modules/unittest/tests.php ; fi

notifications:
  irc:
    channels:
      - "irc.freenode.org#kohana"
    template:
      - "%{repository}/%{branch} (%{commit}) - %{author}: %{message}"
      - "Build details: %{build_url}"
  email: false
